/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>

#ifndef __V89JNI__
#define __V89JNI__

#ifdef __cplusplus
extern "C"
{
#endif

JNIEXPORT void JNICALL Java_V89JNI_startV89 (JNIEnv *env, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif

#endif /* __V89JNI__ */
